version: "3"
services:
  postgresql:
    image: postgres:15.4
    container_name: postgres_db_labs
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: infosys
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    networks:
      - postgresql_bd_net

  minio:
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    volumes:
      - minio-storage:/data
    networks:
      - postgresql_bd_net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

#  backend:
#    container_name: backend
#    build: ./backend/infosys
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgresql
#    environment:
#      POSTGRES_SERVER: postgresql
#      POSTGRES_PORT: 5432
#      POSTGRES_DB: infosys
#      POSTGRES_USER: admin
#      POSTGRES_PASSWORD: password
#    networks:
#      - postgresql_bd_net
#
#  frontend:
#    container_name: frontend
#    build: ./frontend
#    ports:
#      - "5173:5173"

networks:
  postgresql_bd_net:
    driver: bridge

volumes:
  postgresql-data:
  minio-storage: