version: "3"
services:
  postgresql:
    image: postgres:15.4
    container_name: postgres_db_labs
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: infosys
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    networks:
      - postgresql_bd_net

  minio:
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    volumes:
      - minio-storage:/data
    networks:
      - postgresql_bd_net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: OUTSIDE://:29092,INTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: OUTSIDE://localhost:29092,INTERNAL://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-topics-generator:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - kafka
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      # blocks until kafka is reachable
      kafka-topics --bootstrap-server kafka:9092 --list
      
      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic send-file-to-parse-and-save-event --replication-factor 1 --partitions 2
      
      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server kafka:9092 --list
      "

#  backend:
#    container_name: backend
#    build: ./backend/infosys
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgresql
#    environment:
#      POSTGRES_SERVER: postgresql
#      POSTGRES_PORT: 5432
#      POSTGRES_DB: infosys
#      POSTGRES_USER: admin
#      POSTGRES_PASSWORD: password
#    networks:
#      - postgresql_bd_net
#
#  frontend:
#    container_name: frontend
#    build: ./frontend
#    ports:
#      - "5173:5173"

networks:
  postgresql_bd_net:
    driver: bridge

volumes:
  postgresql-data:
  minio-storage: